### ISSUE TITLE
Finish all API Gateway endpoints and corresponding Lambda functions

### ISSUE THREAD

**Issue by chef-louis** [AthletiFi/athletifi-website#126]
**BOLD** items remain as to-do
- - playerProfile (add season highlights + bio)
- matchesList
- latestMatch
- matchDetails (includes s3 bucket link for videos)
- **playerStats**
   - latestStats
   - **statsTrend** (waiting on ratings table tracking historical values)
- teammates
- **topActionReels** (highlight clips)

**Comment by chef-louis** [comment]
- Added bio data to playerProfile

**Comment by chef-louis** [comment]
@qisforq When will we have player rating data (or even just the table structure) in the database? I think that's a blocker to building out the Lambda + API Gateway for the player stats.

**Comment by qisforq** [comment]
> [@qisforq](https://github.com/qisforq) When will we have player rating data (or even just the table structure) in the database? I think that's a blocker to building out the Lambda + API Gateway for the player stats.

Gotcha - the table's are autogenerated based on the calculation logic so I'm not able to make the table structure without the calculations, which I need Pili for. But she'll have some free time this weekend so I can work with her on it then.

**Comment by chef-louis** [comment]
* Added latest player stats
* Added Season Highlights
