### ISSUE TITLE
Update Highlights Video Player to limit access to larger video

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#164]
### Objective
Research how to implement highlights video player so that it appears as an individual video and not a bookmark for the full game recap video.

- [ ] Research video player libraries or plugins that support playing video segments based on timestamps.
- [ ] Explore feasibility of implementing a custom video player component that accepts the start and end timestamps as parameters.
- [ ] If no feasible options are available in front-end, evaluate methods for processing highlight videos as separate videos in AWS.

**Comment by chef-louis** [comment]
One option is to use the Mux video API to create a trimmed video via a POST request (eg. https://www.youtube.com/watch?v=KqgpLpDJjjM)

**Comment by chef-louis** [comment]
Mux also handles thumbnail/poster generation on-demand which is really cool: https://docs.mux.com/guides/get-images-from-a-video

Basically we'll need to set an image src as something like this: `https://image.mux.com/{PLAYBACK_ID}/thumbnail.png?width=400&height=200&fit_mode=smartcrop&time=35`

**Comment by qisforq** [comment]
Investigate the API endpoint to generate video clips on Mux
