### ISSUE TITLE
Link 'Report a Problem' and 'Send an Email' to Send Emails with Prepopulated Content

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#181]
### Objective:
Integrate the "Report a Problem" and "Send an Email" features to send emails with prepopulated content. Dependent on #179.

#### Tasks:

- [x] Create email templates for "Report a Problem" and "Send an Email" with appropriate subject lines and body content.
- [ ] Update the "Report a Problem" and "Send an Email" sections on the Help & Support page to include forms or input fields for users to provide additional details or messages.

**Comment by HectorAgudelo** [comment]
let me know for this one as well
