### ISSUE TITLE
AI text generation for match summary

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#233]
#### Objective
Develop the back-end logic for generating, storing, and serving the "Match Summary" text (#112) using Amazon Bedrock and update the database schema accordingly.

#### Tasks

1.TBD (waiting on example data from sports tagger to understand how timestamp data is structured)

![Image](https://github.com/AthletiFi/athletifi-website/assets/33239211/a173b147-378f-411b-8ae3-3757190f7315)

**Comment by HectorAgudelo** [comment]
parameters to be used from database to feed the AI prompt: this is from 
 **match_results** table: match_result, weather_info, home_team_score, away_team_score, total_duration_in_minutes, overtime, and penalty_kicks.
this is from **matches** table: date, location. this is from the **teams** table: age_group, league, team_name, head_coach. this is from **coaches** table: first_name, last_name. this is from the **league** table: league_name

**Comment by HectorAgudelo** [comment]
const { Client } = require('pg');
const { BedrockRuntimeClient, InvokeModelCommand } = require("@aws-sdk/client-bedrock-runtime");

// Database connection
const dbClient = new Client({
  user: process.env.DB_USER,
  host: process.env.DB_HOST,
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  port: process.env.DB_PORT,
});

// AWS Bedrock client
const bedrockClient = new BedrockRuntimeClient({ region: "us-east-1" }); // adjust region as needed

// SQL query
const query = `
  SELECT 
    mr.match_id,
    mr.match_result,
    mr.weather_info,
    mr.home_team_score,
    mr.away_team_score,
    mr.total_duration_in_minutes,
    mr.overtime,
    mr.penalty_kicks,
    m.date,
    m.location,
    ht.age_group AS home_team_age_group,
    ht.league AS home_team_league,
    ht.team_name AS home_team_name,
    hc.first_name AS home_coach_first_name,
    hc.last_name AS home_coach_last_name,
    at.age_group AS away_team_age_group,
    at.league AS away_team_league,
    at.team_name AS away_team_name,
    ac.first_name AS away_coach_first_name,
    ac.last_name AS away_coach_last_name,
    l.league_name
  FROM 
    match_results mr
  JOIN matches m ON mr.match_id = m.match_id
  JOIN teams ht ON m.home_team_id = ht.team_id
  JOIN teams at ON m.away_team_id = at.team_id
  JOIN coaches hc ON ht.head_coach = hc.coach_id
  JOIN coaches ac ON at.head_coach = ac.coach_id
  JOIN league l ON ht.league = l.league_id
`;

// Function to generate summary using Bedrock
async function generateSummary(matchData) {
  const prompt = `
    Generate a summary for the following match:
    Date: ${matchData.date}
    Location: ${matchData.location}
    Home Team: ${matchData.home_team_name} (Age Group: ${matchData.home_team_age_group}, League: ${matchData.league_name})
    Away Team: ${matchData.away_team_name} (Age Group: ${matchData.away_team_age_group}, League: ${matchData.league_name})
    Score: ${matchData.home_team_score} - ${matchData.away_team_score}
    Weather: ${matchData.weather_info}
    Duration: ${matchData.total_duration_in_minutes} minutes
    Overtime: ${matchData.overtime ? 'Yes' : 'No'}
    Penalty Kicks: ${matchData.penalty_kicks ? 'Yes' : 'No'}
    Result: ${matchData.match_result}
  `;

  const params = {
    modelId: "anthropic.claude-v2",
    contentType: "application/json",
    accept: "application/json",
    body: JSON.stringify({
      prompt: `Human: ${prompt}\n\nAssistant: Here's a summary of the match:`,
      max_tokens_to_sample: 300,
      temperature: 0.7,
      top_p: 1,
    }),
  };

  const command = new InvokeModelCommand(params);
  const response = await bedrockClient.send(command);
  const responseBody = JSON.parse(new TextDecoder().decode(response.body));
  return responseBody.completion;
}

// Main Lambda function
exports.handler = async (event, context) => {
  try {
    await dbClient.connect();

    const { rows } = await dbClient.query(query);

    for (const row of rows) {
      const summary = await generateSummary(row);

      // Update the database with the new summary
      await dbClient.query(
        'UPDATE match_results SET summary = $1 WHERE match_id = $2',
        [summary, row.match_id]
      );
    }

    return { statusCode: 200, body: JSON.stringify('Summaries generated and stored successfully') };
  } catch (error) {
    console.error('Error:', error);
    return { statusCode: 500, body: JSON.stringify('Error processing matches') };
  } finally {
    await dbClient.end();
  }
};
