### ISSUE TITLE
Cleanup Unused Code and Artifacts

### ISSUE THREAD

**Issue by chef-louis** [AthletiFi/athletifi-website#24]
Review the entire codebase, identify and remove any unused code, libraries, components, or artifacts that are no longer necessary.

- [x] Remove unused comments at the bottom of `~/components/common/Header.tsx`.
- [x] Delete the unused file `~/src/pages/api/hello.ts` after ensuring no dependencies.
- [x] Eliminate unused dummy data in `~/components/common/Helper.tsx`.
- [x] Define or remove the undefined CSS class "overflow_anchor".
- [x] Correct types such as "SAMLL SREEN MENUICONS", "BlueShodow", and "UnderLIneText".
- [x] Rename old references to NFT, like "right-nft-image", to match current project context.

**Comment by chef-louis** [comment]
@qisforq the `RecentNewsInsights` component contains dummy data and is commented out within the `[slug].js` file so that data isn't being used anywhere. I was going to delete it but I wasn't sure if this component has already been replaced or if you're planning to have a replacement in the future. If it's helpful to keep for a future replacement, I don't have to delete it yet.

**Comment by chef-louis** [comment]
I'll leave it in there for now, but can easily remove it after it's confirmed we don't need it anymore.

**Comment by qisforq** [comment]
Sorry for the late response @chef-louis. That is a leftover for sure. NewsInsightsCards replaced it, so it can be deleted!

**Comment by qisforq** [comment]
I'll review this PR later today and merge

**Comment by chef-louis** [comment]
Okay great, I'll get that code deleted now so you can review the updates in full.
