### ISSUE TITLE
Create documentation for AthletiFi's AWS environment

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#244]
### Objective
Create Documentation of AthletiFi's AWS environment. This would be for internal use, mainly to help us keep track of the services in use and their purpose. 

### Services to document

1. Lambda Functions
2. RDS Database
3. API Gateway
4. Secrets Manager
5. Cognito
6. Amplify 
    - for hosting
    - for Auth connection with Cognito
    - Use case for backend UI

**Comment by chef-louis** [comment]
Created an MS document via Teams [Backend Documentation](https://athletifi-my.sharepoint.com/:w:/g/personal/louis_athleti_fi/EU1aYbKBJXpOmIDR0VB9x6sBTN1Tc8HI4MQxt6rKy4zR_g?e=tCBAAE)
