### ISSUE TITLE
Improve Error handling in functions

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#25]
(See [Error Handling](https://nextjs.org/docs/pages/building-your-application/configuring/error-handling) section of Next.js docs)

1. **Enhance error feedback mechanism for POST requests in `components/common/api/Api.tsx`**:
   - [x] Update the `postRequestHandler` to include detailed error logging, specifically indicating which part of the request failed, such as connection issues or data validation errors.
   - [x] Example: Log a message like "POST request to /api/newsletter failed: Server did not respond" in case of a connection timeout.

2. **Handle server response errors with specific messages in `components/common/api/Api.tsx`**:
   - [x] Modify the error handling to parse server response errors and convert them into meaningful, readable messages.
   - [x] Example: If the server returns a 404 error, display "The requested resource was not found."

3. **Implement null safety and fallbacks for missing data in `pages/news/[slug].js`**:
   - [x] In `getServerSideProps`, check for null or undefined values in the response data and provide a default fallback value.
   - [x] Example: If `newsDetailData` is null, set it to an empty object or a predefined error state.

4. **Add specific error handlers for different types of request failures in `pages/news/index.js`**:
   - [x] Distinguish between different HTTP errors (like 404, 500) and handle them with tailored responses.
   - [ ] Example: On a 500 error, log "Internal Server Error" and redirect the user to a custom error page (See [create custom 404 page]()).

5. **Ensure graceful handling of HTTP errors and display appropriate user messages in `components/common/api/Api.tsx`**:
   - [ ] Implement a user-friendly error message system that informs users about the error in a non-technical language.
   - [ ] Example: For a 503 Service Unavailable error, display "The service is temporarily unavailable. Please try again later."

6. **Handle server response errors and inform the user appropriately in `components/sign-up/SignUpForm.tsx`**:
   - [x] Create a mechanism to notify users about specific errors encountered during form submission.
   - [x] Example: If the email address is already in use, display a message like "This email address is already registered."

7. **Enhance comprehensive error response handling for different HTTP statuses in `components/common/api/ApiHelper.tsx`**:
   - [x] Map different HTTP status codes to custom error messages or actions.
   - [x] Example: On a 401 Unauthorized error, log the user out or redirect to the login page.

8. **Introduce error boundaries in React components for robust error handling**:
   - [x] Implement React error boundary components to catch JavaScript errors anywhere in the child component tree.
   - [x] Example: Wrap main page components in an error boundary to prevent the entire app from crashing.
   - See [section on Error Boundaries in React docs](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary) for more guidance.

9. **Ensure detailed error logging for server-side data fetching issues in `pages/news/[slug].js`**:
   - [ ] Log detailed error information, including timestamps and the nature of the error, when server-side data fetching fails.
   - [ ] Example: Log "Failed to fetch news details at [timestamp], error: [error message]."

10. **Implement fallback UI components in case of data fetch failure in `pages/news/[slug].js`**:
    - [ ] Design and implement UI components that are displayed when data fetching fails, informing the user of the issue.
    - [ ] Example: Display a message like "Unable to load news details. Please try refreshing the page."

**Comment by chef-louis** [comment]
Notes for future reference:
- Error handling is included for any of the asynchronous code (ie. http requests via axios) along with translating error codes into human-readable messages.
- Error Boundaries are built for Server Side Rendering and Asynchronous code which accounts for most of our current Error Boundary use-cases. The `ErrorBoundary.tsx` class is included in this PR but isn't utilized within any of the pages yet. Leaving it in for potential future use.
