### ISSUE TITLE
Refactor animation code

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#29]
Examine all animation implementations and refactor for efficiency.

- [ ] Develop a centralized animation helper function in `src/utils/animationHelpers.ts`.

- [ ] Replace existing animation code in `HeroHomepage.tsx` with the new animation helper function.

- [ ] Implement the animation helper function in `WhoWeAre.tsx`, `OurMission.tsx`, and `LookingForward.tsx` components.

- [ ] Use the animation helper function in `NewsInsightsCards.tsx` and `FocusArticle.tsx`.

- [ ] Integrate animation helper in `SignUpForm.tsx`.

- [ ] Refactor common components like `Header.tsx` and `Footer.tsx` to use the animation helper.

- [ ] Review and optimize animations defined in Tailwind CSS configurations.

**Comment by chef-louis** [comment]
@qisforq maybe I'm thinking about this incorrectly but I was thinking of this refactoring more as a reusable component with the most common animation configs as the default option, allowing for overrides to tweak the desired animation.

I'm trying to better understand how this would work with a helper function. Would the helper function be outputting the desired animation settings for each page or component? I think that could work as well but wanted to make sure I understood this correctly.

**Comment by chef-louis** [comment]
Marking this tasks as OBE given the upcoming dashboard focused design changes.
