### ISSUE TITLE
Build Unit Tests

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#30]
Write and implement unit tests for critical components and functions.

- [ ] Research best testing frameworks to use (Storybook + Jest is common for Next.js projects)
- [ ] **Setup Testing Framework** - Add and configure chosen Testing Library and set up a basic configuration.

#### Suggested tests:
- [ ] **Unit Test for Header Component** - Create `Header.test.tsx` in `src/components/common/Header/`, testing rendering and verifying all links are present.
- [ ] **Unit Test for Footer Component** - Create `Footer.test.tsx` in `src/components/common/Footer/`, testing rendering and verifying all footer content.
- [ ] **Unit Test for CommonHero Component** - Create `CommonHero.test.tsx` in `src/components/common/CommonHero/`, testing rendering with different props.
- [ ] **Unit Test for API Utility Functions** - Create `ApiHelper.test.tsx` in `src/components/common/api/`, testing all functions for correct API calls and error handling.
- [ ] **Unit Test for SignUpForm Component** - Create `SignUpForm.test.tsx` in `src/components/sign-up/`, testing form submission and input validation logic.
- [ ] **Unit Test for NewsInsightsCards Component** - Create `NewsInsightsCards.test.tsx` in `src/components/news-insights/`, testing rendering of news cards and pagination.
- [ ] **Unit Test for Home Page Components** - Create `Home.test.tsx` in `src/pages/`, testing rendering of all key components on the homepage.
- [ ] **Integration Test for Navigation Flow** - Create `Navigation.test.tsx` in `src/tests/`, testing navigation flow between different pages.
- [ ] **Testing Utilities Setup** - Create `test-utils.tsx` in `src/tests/`, setting up custom render functions and other utilities for testing.

**Comment by qisforq** [comment]
Marking this task as OBE now that we have an epic for it -  #407

**Comment by chef-louis** [comment]
* Added more detailed tasks in #514 and #515. Closing this task as duplicate
