### ISSUE TITLE
Start loading in REAL player data

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#320]
Player names, parent emails, Placeholder card image, etc

**Comment by chef-louis** [comment]
Loaded 66 players into `player_identities` table. A couple items of note:
- some players are duplicated (ie. they had a test entry before which I'm keeping for testing purposes Ex. "Hunter Ormsbee". Can clean up test entries later)
- Only one parent's information available in player data

Follow-up questions:
1. What should we use as the slug handle for Summer Select? `ss-24`?
2. Do we have QR code mappings to `card_id`s that we need to follow (similar to what we had to do for vsa-23)?

To-do items:
- Add [club, league, coaches, players_team_info, team_coaches, teams] for Summer Select

**Comment by qisforq** [comment]
> 66 players total (5 more than initially thought) -- is that correct?

Hmm, it looks like 66 is actually correct now (that's what the AthletiFiSelectSignups excel sheet is showing now as well). We did have some last minute signups, and I guess they didn't get pulled into the excel sheet at the time I shared the 61 figure with you.

> What should we use as the slug handle for Summer Select? ss-24?
I was about to suggest the abbreviation for AthletiFi Summer Select, but after seeing it written out, `ss-24` is definitely the way to go 😂

Or we can make it more human readable and do `summer-select-24`?

> Do we have QR code mappings to card_ids that we need to follow (similar to what we had to do for vsa-23)?

Nope, the issue last time is that the cards were printed before the application existed, so we had to make a best guest to how the url's would be crafted. This time around we will create the QR codes afterward

**Comment by chef-louis** [comment]
`summer-select-24` it is!

Makes sense on the QR codes. Thanks for the context.

**Comment by chef-louis** [comment]
@qisforq More follow-up notes/questions by table

`public.clubs`
- Added 1 club = `AthletiFi Summer Select`
- What is the location?
- Do we have a logo svg?

`public.league`
- Not sure for this one. Is this some generic `AthletiFi Summer Select League`?

`public.teams`
- With the 66 player roster, how many teams does this represent and what are their names (ie. `Summer Select U12`, `Summer Select U14`, etc)?

`public.coaches`
- It looks like there are 4 coaches in total (Darren John, AJ, Brian and Justin -- I don't have last names for the last 3 so left blank for now) 

`public.team_coaches`
- Using the responses from above, what are the mappings of teams <> coaches? If this is fluid, what inputs should I use here for now?

`public.players_team_info`
- I can fill in most of this table with the initial player dataset and questionnaire, but currently missing player numbers (will leave blank for now)

`public.player_card_images`
- I'll leave `card_image_url` blank for now
- Any preference for how to arrange `dashboard_slug`? Is a sequential ordering of slug okay (ie. alphabetically increasing example `summer-select-24/1`, `summer-select-24/2`, `summer-select-24/3`, etc.)?

**Comment by chef-louis** [comment]
Basic data entries made to the following tables for all 66 players:
- `public.clubs`
- `public.league`
- `public.coaches`
- `public.teams`
- `public.team_coaches`
- `public.players_team_info`
- `public.player_card_images`

data points left blank where appropriate and/or filled in with placeholder values for now. Will update based on responses above.

**Comment by qisforq** [comment]
`public.clubs`
> - What is the location?
Glenside, PA
> - Do we have a logo svg?
Yes, I uploaded it into the s3 bucket: https://athletifi-s3.s3.us-east-2.amazonaws.com/logos/athletifi-select-logo.svg

`public.league`
> - Not sure for this one. Is this some generic `AthletiFi Summer Select League`?
Good question! Perhaps just put 'independent'?

`public.teams`
> - With the 66 player roster, how many teams does this represent and what are their names (ie. `Summer Select U12`, `Summer Select U14`, etc)?
For the tournaments we have them listed as 3 teams: Athletifi Select '11, AthletiFi Select '12, AhtletiFi Select '14. Just FYI all the players with 2012 or 2013 birth years go into AthletiFi Select '12, and all the players with 2014 or 2015 birth years go into AthletiFi Select '14. Not sure if we need to, buy we may want to separate by boys and girls. If so we can make `AthletiFi Select '12G` or `AthletiFi Select 12 Girls`, etc.

`public.coaches`
> - It looks like there are 4 coaches in total (Darren John, AJ, Brian and Justin -- I don't have last names for the last 3 so left blank for now) 
AJ is actually Ashley Johnson. Perhaps put his first name as `Ashley "AJ"`, so that way the full name gets rendered as `Ashley "AJ" Johnson`. Then it's Brian Blasy and Justin Johnson

`public.team_coaches`
> - Using the responses from above, what are the mappings of teams <> coaches? If this is fluid, what inputs should I use here for now?
AJ coaches 2012 boys
Justin coaches 2012 girls
Brian coaches 2014 girls
Darren coaches 2011 boys.

`public.players_team_info`
> - I can fill in most of this table with the initial player dataset and questionnaire, but currently missing player numbers (will leave blank for now)
I have some of the jersey numbers written down on the attendance sheet from the practices this week, but not all because not everyone has received a shirt yet. I will update you when I get this info digitized.

`public.player_card_images`
> - I'll leave `card_image_url` blank for now
> - Any preference for how to arrange `dashboard_slug`? Is a sequential ordering of slug okay (ie. alphabetically increasing example `summer-select-24/1`, `summer-select-24/2`, `summer-select-24/3`, etc.)?
I think a sequential ordering should be fine. That is how we handled the last collection. Whatever you think is best!

**Comment by chef-louis** [comment]
Great, thanks @qisforq. I've incorporated your edits into the database

**Comment by chef-louis** [comment]
- Uploaded a `placeholder_card.png` file to serve as the temporary player card while actual card images get sorted.
- `https://athletifi-s3.s3.us-east-2.amazonaws.com/player-card-images/placeholder_card.png`

**Comment by qisforq** [comment]
Last ditch effort is to complete #313 to see if that fixes the issue

**Comment by qisforq** [comment]
Match videos from Hershey were uploaded https://us-east-2.console.aws.amazon.com/s3/buckets/athletifi-s3?region=us-east-2&bucketType=general&prefix=match_videos/

I'll add them into the database as well

**Comment by chef-louis** [comment]
@qisforq It looks like the lambda function for uploading S3 videos into Mux didn't run properly. Taking a look into why that failed and then will retrigger

**Comment by chef-louis** [comment]
It takes Mux a very long time to process the full length match videos (30+ minutes). The path forward here is to de-couple the upload of videos to Mux and writing the relevant video details to our postgres database once the Mux upload is fully processed.

**Comment by chef-louis** [comment]
Mux videos have now successfully loaded (most taking between 30 minutes and 1 hour to process) and relevant data entries into `full_match_videos` have been written by a manual run of the lambda function.

`match_result_id`s have also been mapped appropriately to the video data.

**Comment by chef-louis** [comment]
@qisforq Adding a reminder here for the additional sign-ups to the Summer Select program that we received. I'll get those folks added into the databases accordingly.

**Comment by chef-louis** [comment]
Added player avatar photos to S3 and mapped all of them to existing player identities (except for 1 with an 'unknown' name).

I've communicated to Jake that we are still missing player avatar photos for 39 players out of the 90 total in our database.
