### ISSUE TITLE
Investigate / Create API endpoint to update invite status to 'revoked'

### ISSUE THREAD

**Issue by chef-louis** [AthletiFi/athletifi-website#322]
Make sure we are able to attach a frontend button to an API endpoint that can update the invite status to be revoked (likely a check/update to an existing lambda function).

@pm-moyanor for reference. I'll investigate and let you know of any updates here.

**Comment by chef-louis** [comment]
@pm-moyanor Okay I've got more info on this for you and I've learned through the process myself. The lambda function `referralInvite` looks for an `action` key that it looks for within the POST request. The available options are  `invite` and `revoke` and the lambda function already handles updating the backend as well as sending out relevant emails to communicate to the users directly. I'm closing out this task as it doesn't require any additional work and should be handled by the existing lambda function. Let me know if you have any issues in hooking up the frontend to use this backend endpoint or are looking for additional clarification.

**Comment by pm-moyanor** [comment]
thank you @chef-louis!
