### ISSUE TITLE
BUG pending invite does not show up on invited user's profile or settings pages

### ISSUE THREAD

**Issue by chef-louis** [AthletiFi/athletifi-website#325]
As of June 17, this bug is found on the `referralDataLogic` branch.

Steps to replicate:
1. Log into a user account that owns a card
2. Invite another (existing) user as a guest on that card
3. Log into the invitee's account WITHOUT using the invite_id
4. See that there is no record of a pending invite for the invitee

**Comment by chef-louis** [comment]
![Image](https://github.com/AthletiFi/athletifi-website/assets/140190642/33bd5f67-09ea-4280-be53-0621ff4065bc)
![Image](https://github.com/AthletiFi/athletifi-website/assets/140190642/5f015a96-a7e6-4cc8-800c-400c0148e2af)
![Image](https://github.com/AthletiFi/athletifi-website/assets/140190642/7f7a52d0-8c35-472f-99af-63e23e033bba)

**Comment by chef-louis** [comment]
@HectorAgudelo @pm-moyanor It looks like these are filtering on `acceptedGuestCards`. Does that mean this behavior is by design? If so we can close this task and mark it as not relevant.

**Comment by HectorAgudelo** [comment]
i think by design, the pending tag is visible only in the owner profile. the invitee can only accept the invitation with the link. they wont see a pending invitation in their profile unless they are sharing one of their cards.

**Comment by HectorAgudelo** [comment]
although, that could be a nice feature to implement in the future.

**Comment by chef-louis** [comment]
Closing out this task as Will Not Fix
