### ISSUE TITLE
Clean-up inviteRevokeAction from atom into route handler

### ISSUE THREAD

**Issue by chef-louis** [AthletiFi/athletifi-website#329]
`inviteRevokeAction` found in `InviteRevokeStore.ts` is currently defined within an atom and doesn't have any state requirements. Refactor this to either use the existing `referralInvite` route handler endpoint or merge this with an existing route.

**Comment by qisforq** [comment]
Related to #332

**Comment by chef-louis** [comment]
Synced up with @HectorAgudelo. We are starting with 2 Server Action related tasks. This will be one of them with Hector driving and Louis to support.

**Comment by qisforq** [comment]
Will be part of the Server Actions PR
