### ISSUE TITLE
Refactor alert on 'sign-up' page

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#33]
Right now if you don't check the 'I agree to all Term, Privacy Policy and Fees' you get an alert that says 'Please checked the condition'

- [x] Refactor the alert to be a 'toast' warning message (see [AthletiFi Select's sign-up form](https://github.com/AthletiFi/athletifi-select-website/blob/main/src/components/sign-up/SignUpForm.tsx) for an example)
- [x] Update message to be more descriptive and accurate (we have no fees)
- [ ] Hyperlink Terms and Privacy Policy pages (Also to be done in this sprint)
- [x] Create warning for 'duplicate email' as well

**Comment by chef-louis** [comment]
- Removed language of any "Fees"
- Added basic error handling of POST request
- Added styling for "Terms of Use" and "Privacy Policy"
- TODO: Need to link the documents as soon as they are available.

**Comment by chef-louis** [comment]
@qisforq Requesting Terms of Use and Privacy Policy documents so I can update the links at sign-up accordingly.

**Comment by qisforq** [comment]
@chef-louis I'll get the documents ready by end of day!

**Comment by qisforq** [comment]
@chef-louis pages in #55, I added you as reviewer
