### ISSUE TITLE
Optimization: Refactor API requests into server actions

### ISSUE THREAD

**Issue by chef-louis** [AthletiFi/athletifi-website#332]
Youtube reference: https://www.youtube.com/watch?v=RadgkoJrhu0

Would allow for quick/easy path revalidation. Also allows for leveraging NextJS caching.
- GET requests can go directly into server components
- POST requests and other mutations can go into server actions

Would clean-up / limit use of state management across the project.

This would make updating our front-end after back-end changes very easy to implement (ie. backend changes such as 'revoking' invite or 'sending invite' should update on the same page as the inviter). Current implementation uses a hard-refresh to update the screen with the latest backend state which is a poor user experience.

**Comment by chef-louis** [comment]
Keeping this as a master task for the following subtasks:
#329 
#373 
#337 >> After adding revalidation into server actions

**Comment by chef-louis** [comment]
Additional requests to refactor:
* Account delete POST request
* User sign-up POST request

**Comment by chef-louis** [comment]
Completed:
- Refactored notifications GET, POST and DELETE into server actions
- Cleaned up profileCardsDataStore

**Comment by qisforq** [comment]
Will be apart of the server actions PR
