### ISSUE TITLE
BUG: Card Data undefined

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#345]
Task: Debug and Fix Dashboard API Data Retrieval Error 
Objective:
Resolve the TypeError occurring in the GET handler of the /api/dashboard/[...cardId] route, specifically for card ID 4, to ensure proper data retrieval and error handling for the AthletiFi dashboard.

Steps:

1. Code Investigation:
   - Examine src/app/api/dashboard/[...cardId]/route.ts, focusing on line 17
   - Identify why the code is attempting to access index [0] of a null value

2. Data Flow Analysis:
   - Trace the data flow for card ID 4
   - Verify if the database query is returning expected results for this specific card

3. Implement Null Checks:
   - Add null checks before accessing any properties of the retrieved data
   - Handle cases where the data might be null or undefined

4. Error Handling:
   - Implement a try-catch block in the GET handler
   - Create an appropriate error response for when data is not found or is null

5. Logging:
   - Add detailed logging to capture the state of the data at each step
   - Log the cardId being processed and any query parameters

6. Testing:
   - Create a test case specifically for card ID 4
   - Ensure the handler works correctly for both card ID 4 and 5 (which seems to be working)

7. Database Query Review:
   - Review and potentially optimize the database query for fetching card data
   - Ensure consistent data structure is returned for all card IDs

8. Code Refactoring:
   - Consider extracting the data fetching logic into a separate function for better maintainability

9. Update API Documentation:
   - Document the possible response scenarios (success, not found, error)
   - Update any API documentation to reflect changes in error handling

10. Pull Request and Code Review:
    - Create a pull request with the changes
    - Provide before and after examples in the PR description

Definition of Done:
- The TypeError is resolved for card ID 4
- The API returns appropriate responses for both existing and non-existing card IDs
- Error handling is in place with informative error messages
- Unit tests pass for various scenarios including card ID 4 and 5
- Code has been reviewed and approved by at least one other team member
- Documentation is updated to reflect the changes

Estimated time: 3-4 hours

Priority: High

Assigned to: [Developer Name]

By completing this task, we will improve the reliability of the AthletiFi dashboard API, ensuring consistent behavior across different card IDs and providing a better experience for users accessing player data.

**Comment by qisforq** [comment]
Add Error handling and optional chaining

**Comment by chef-louis** [comment]
I'm not able to reproduce the same error on my local setup. Will coordinate with @qisforq to resolve the issue and see if there are any deeper problems that need fixing.
