### ISSUE TITLE
Update 'Trusted Partners' section

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#35]
- [x] Remove Eyeball
- [x] Add new partners
- [x] Add hyperlinks

**Comment by qisforq** [comment]
@qisforq to share logos with @pm-moyanor 

- VSA
- IQSelect
- Scott's program
- AJ's
-

**Comment by qisforq** [comment]
![Image](https://github.com/AthletiFi/athletifi-website/assets/33239211/abe67126-b115-4f51-9daa-2e6bdfc827bd)
![Image](https://github.com/AthletiFi/athletifi-website/assets/33239211/0ec2bf70-dd12-4f4a-989c-e70b0d9b35f4)
![Image](https://github.com/AthletiFi/athletifi-website/assets/33239211/f0205ce5-fab5-40f8-aff8-956375a15bb4)
![Image](https://github.com/AthletiFi/athletifi-website/assets/33239211/115245b4-782a-421d-a7e6-644fc2a6ff28)

**Comment by qisforq** [comment]
@pm-moyanor I wrote in a comment I would share the above icons with you, so I just added them here

**Comment by qisforq** [comment]
![Image](https://github.com/AthletiFi/athletifi-website/assets/33239211/ffb38bb5-8ffc-44f3-ab77-fce36cad3b12)
![Image](https://github.com/AthletiFi/athletifi-website/assets/33239211/c116b6fd-3c46-4377-bb54-bc8c711b5d5c)
![Image](https://github.com/AthletiFi/athletifi-website/assets/33239211/d2e3f742-d133-485d-9701-5959f7130fcb)



![Image](https://github.com/AthletiFi/athletifi-website/assets/33239211/6516ca9c-0479-4b37-9684-999fa1bbc825)

**Comment by pm-moyanor** [comment]
Great thanks @qisforq
