### ISSUE TITLE
Create dev support email / distro and update account deletion requests to be sent there

### ISSUE THREAD

**Issue by chef-louis** [AthletiFi/athletifi-website#361]
1. Create dev support email / distro list
2. Update lambda function `deleteUserDataRequest` to send account delete request to new email

**Comment by chef-louis** [comment]
Quentin made a developer email list [developers@athleti.fi](mailto:developers@athleti.fi) and this is now the recipient on delete requests within the lambda function `deleteUserDataRequest`

**Comment by qisforq** [comment]
Thanks for the update!
