### ISSUE TITLE
Add Player data for additional Summer Select players

### ISSUE THREAD

**Issue by chef-louis** [AthletiFi/athletifi-website#367]

**Comment by qisforq** [comment]
[player-jerseys.csv](https://github.com/user-attachments/files/16060350/player-jerseys.csv)
Here are the jersey numbers for most of the players. There are some missing which I am working on finding

**Comment by chef-louis** [comment]
> [player-jerseys.csv](https://github.com/user-attachments/files/16060350/player-jerseys.csv) Here are the jersey numbers for most of the players. There are some missing which I am working on finding

Thanks I'll get this data into the database

**Comment by chef-louis** [comment]
Updated most where player identities existed. The following player data has not yet been entered (either need more data for player identities or missing a player number):

<google-sheets-html-origin><style type="text/css"></style>
First Name | Last Name | DOB | Jersey Number
-- | -- | -- | --
Filipe | Cruz | 05/21/2011 | 12
Nickollas | Nascimento | 08/17/2011 | 0
Asher | Mcintyre | 01/18/2012 | 37
Robert | Nyemscek | 07/11/2012 | 8
Nolan | Schaeffer | 08/16/2012 |  
Luca | Yencha | 3/29/11 | 35
Oscar | Gasga |   | 43

**Comment by qisforq** [comment]
Oscar Gasga should actually have a record I believe. I'll find the needed data for the rest of them

**Comment by qisforq** [comment]
[new_players.csv](https://github.com/user-attachments/files/16071726/new_players.csv)
Hey @chef-louis, here is a csv with info on all of the new players. I believe I got all of them. If there are any players still missing please let me know

Just fyi not all of these players actually received shirts yet so we won't actually have jersey numbers to record for a lot of them

**Comment by chef-louis** [comment]
I see the player_identity for Oscar Gasga which I'll use. Also adding in the others that are new. I'll report back with anything missing here.

**Comment by chef-louis** [comment]
@qisforq Additional 24 players have been added into the database -- that leaves a total of 90 for Summer Select.

I double checked the lists and I don't see Oscar Gasga as being a participant in Summer Select. I see a Kimberly Gasga (I'm guessing they're related) who is registered though. Let me know if I'm missing something here.

Factoring in all the Summer Select players, we are still missing numbers for about half of the players:

<google-sheets-html-origin><style type="text/css"></style>
Player Name
--
Ahmed Abdelgadir
Ewan Abhulimen
Asher Blaney
Mia Bongard
Anthony Bonilla
Jeffrey Bonilla
Maxwell Breeden
Charlotte Caine
Lydia Carlin
Katherine Cole
Maeve Cooney
Dangkhoa Dang
Evan Davis
Josiah Felix
Michael Fisher
Evelyn Fritton
Andrew Gilmour
Harrison Glover
Mia Guglielmelli
Maura Hagarty
Quinn Hanrahan
Giuliana Hanuscin
Vincent He
Christian Hill
Mithul Manoharan
Hudson Marsh
Joaquin Martin
Stella Morris
Munotidaishe Ryan Mutubuki
Mioree Neal
Bryan Nihart
Keira Pownall
Tina Pownall
Natalie Price
Anderson Rodriguez
Benjamin Rodriguez
Nolan Schaeffer
Kieran Seehra
Logan Sharrock
Sinaly Sidibe
Joi Smith
Grady Smith
Esteban Vidal
Lucy Wojcik
Reagan Yeck
Lucas Zimmerman

**Comment by chef-louis** [comment]
Also with 90 players with wider age ranges, it looks like there will be more teams. If you can add to the existing list of teams I can update the player's relevant teams accordingly:

- AthletiFi Select '14 Girls
- AthletiFi Select '12 Girls
- AthletiFi Select '12 Boys
- AthletiFi Select '11 Boys

**Comment by qisforq** [comment]
> [@qisforq](https://github.com/qisforq) Additional 24 players have been added into the database -- that leaves a total of 90 for Summer Select.
> 
> I double checked the lists and I don't see Oscar Gasga as being a participant in Summer Select. I see a Kimberly Gasga (I'm guessing they're related) who is registered though. Let me know if I'm missing something here.
> 
> Factoring in all the Summer Select players, we are still missing numbers for about half of the players:
> 
> ## Player Name
> Ahmed Abdelgadir Ewan Abhulimen Asher Blaney Mia Bongard Anthony Bonilla Jeffrey Bonilla Maxwell Breeden Charlotte Caine Lydia Carlin Katherine Cole Maeve Cooney Dangkhoa Dang Evan Davis Josiah Felix Michael Fisher Evelyn Fritton Andrew Gilmour Harrison Glover Mia Guglielmelli Maura Hagarty Quinn Hanrahan Giuliana Hanuscin Vincent He Christian Hill Mithul Manoharan Hudson Marsh Joaquin Martin Stella Morris Munotidaishe Ryan Mutubuki Mioree Neal Bryan Nihart Keira Pownall Tina Pownall Natalie Price Anderson Rodriguez Benjamin Rodriguez Nolan Schaeffer Kieran Seehra Logan Sharrock Sinaly Sidibe Joi Smith Grady Smith Esteban Vidal Lucy Wojcik Reagan Yeck Lucas Zimmerman

Ahh Oscar Gasga never actually signed up, but has been showing up for the practices. We'll need his info though so I'll work on that
