### ISSUE TITLE
Implement data ingestion for match events and player minutes CSVs from Data Tagging Company

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#393]
### Description:
Create a Lambda function to process CSV files received via email from Flatworld. The function should:

1. Set up an email trigger using AWS SES to receive emails with CSV attachments.
2. Process two types of CSV files:
   a. Match event data CSV
   b. Minutes played CSV
3. For the match event data CSV:
   - Parse the CSV and insert records into the `match_events` table.
   - Include fields such as `match_id`, `player_id`, `video_timestamp`, `event_type`, and `is_goalkeeper`.
   - Convert the video timestamp format from the CSV to the correct interval format for the `video_timestamp` field.
4. For the minutes played CSV:
   - Parse the CSV and insert/update records in the `match_attributes_per_player` table.
   - Specifically update the `minutes_played_outfield` and `minutes_played_goalkeeper` fields.
5. Implement a whitelist feature to ensure only authorized email addresses can trigger the function.
6. Include error handling and logging for any issues encountered during the ingestion process.

Key considerations:
- Ensure proper mapping of player information from the CSV to the corresponding `player_id` in our database.
- Implement a check to see if a record already exists in the `match_attributes_per_player` table before inserting or updating.
- Ensure the function can handle concurrent requests if multiple CSVs are received simultaneously.
- Use AWS best practices for Lambda function development and deployment.
- Implement checks to avoid duplicate data insertion.

**Note:** this task is related to #394

**Comment by qisforq** [comment]
#392

**Comment by chef-louis** [comment]
Player minutes data will be written into `match_attributes_per_player`table. Lambda function will need to check if a row on match / player already exists and update the row if so, if not create another row entry

**Comment by chef-louis** [comment]
Subdomain `data.import.athleti.fi` is now verified on SES. Next is to add filters and rules to process emails with attached CSVs.

**Comment by chef-louis** [comment]
Issues with data during automated upload:
- Flatworld returns a few "UNKNOWN PLAYER" entries (but includes player number which can be helpful in figuring out who the player might be).
- Guest players who normally play on other teams can cause issues when trying to match up players. Currently requires adding a new `player_id` entry into `players_team_info` or the player lookup fails
- Requires a pre-processing check on the following:
  - Team names (they need to match up with the names in our `teams` database)
  - Event types need to match up exactly
  - Time formatting needs to be in an interval format (HH:MM:SS)

**Comment by chef-louis** [comment]
Otherwise, the data for the three 2011 boys matches are uploaded into the database

**Comment by chef-louis** [comment]
Data ingestion logic is complete. Will track the email triggering in task #394
