### ISSUE TITLE
Implement main processing Lambda function for match data ingestion

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#394]
AKA Create a lambda function for processing csv and inserting match events (insert_match_event).
### Objective
Create a Lambda function that will serve as the main entry point for processing match event and player minutes data. This function will orchestrate the entire ingestion and processing workflow. Explore various options for triggering the data ingestion process, with a focus on security, ease of use, and reliability. Consider email-based triggers as well as other potential solutions.

### Sub-tasks
1. Set up a new Lambda function in AWS.
2. Implement the main processing logic:
   - Read input data (CSV files for events and minutes).
   - Call insert_match_event for each event.
   - Process player minutes data.
   - Trigger aggregate_match_events function.
3. Implement a mechanism to save the original CSV files to an S3 bucket for backup.
4. Research and evaluate the following ingestion trigger options:
   a. Email-based trigger:
      - Investigate AWS SES (Simple Email Service) for receiving emails.
      - Explore how to securely set up an email address for receiving CSVs.
      - Research best practices for email attachment handling and security.
   b. S3-based trigger:
      - Evaluate using S3 event notifications to trigger the Lambda function.
      - Consider setting up a dedicated S3 bucket for file uploads.
   c. API Gateway trigger:
      - Investigate creating a secure API endpoint for file uploads.
      - Research authentication and authorization methods for the API.
   d. AWS Transfer for SFTP:
      - Evaluate using SFTP for secure file transfers.
      - Research how to integrate SFTP with Lambda triggers.

**note:** this task is related to #393

**Comment by chef-louis** [comment]
Currently skipping the email trigger and attachment parsing. I've skipped to uploading CSVs directly to S3 and triggering from there for now until we have the rest of the flow working.

**Comment by chef-louis** [comment]
Closing this for now. Adding another task to track addition of SES email triggering
