### ISSUE TITLE
Create initial basic wireframes for Coach's Portal

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#433]
Goal of this task is to create a very basic wireframe that can be completed by the end of sprint 10

**Comment by chef-louis** [comment]
UPDATE: progress/scope has evolved greatly here as we have opted to first codify requirements and initial inputs from the coaches

**Comment by chef-louis** [comment]
Closing this task and recreating another for the next round of designs/wire-frames
