### ISSUE TITLE
Investigate unit testing frameworks and process

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#434]
Our NextJS application needs programmatic testing for future stability and scalability. Throughout the course of this spike, we should:
1. Investigate popular unit-testing frameworks
2. Form an opinion on the process to incorporate/build unit-testing into the application's code base.

**Comment by chef-louis** [comment]
Various options for [NextJS testing](https://nextjs.org/docs/app/building-your-application/testing):
 - Vitest (Unit testing)
 - Jest (Unit testing)
 - Playwright (E2E testing)
 - Cypress (E2E testing)
