### ISSUE TITLE
Create a trigger function for aggregating match events (aggregate_match_events)

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#436]
## Description
Develop a PostgreSQL trigger function that automatically aggregates match events and updates the `match_attributes_per_player` table when new records are inserted into the `match_events` table. This function is a critical component of the data processing pipeline for the AthletiFi platform.

The function should:
1. Listen for INSERT operations on the `match_events` table.
2. Aggregate the event data for each player and match combination.
3. Look up the corresponding record in the `match_attributes_per_player` table using the `player_id` and `match_id`.
4. Update the relevant fields in the `match_attributes_per_player` table with the aggregated data. This includes fields such as:
   - `dribbles_total`, `dribbles_success`
   - `passes_total`, `passes_success`
   - `cross_total`, `cross_success`
   - `shots_on_target`, `shots_total`
   - `goals_scored`, `assists`
   - And other relevant fields as per the event types
5. Handle cases where a record might not exist in the `match_attributes_per_player` table (e.g., if the minutes played data hasn't been processed yet) and create a new record if necessary.

## Key considerations
- Ensure the trigger function is efficient and doesn't cause performance issues on the database.
- Implement proper error handling and logging within the function.
- Consider concurrency issues and ensure the function can handle multiple events being inserted simultaneously.
- Optimize for performance, especially when dealing with large numbers of events.
- Test thoroughly to ensure data integrity across both the `match_events` and `match_attributes_per_player` tables.
- Implement the function with scalability and reliability in mind, as it will be a core component of the data processing pipeline.
- Ensure the function can work correctly with the minutes played data that should already be present in the `match_attributes_per_player` table.

This task is critical for processing the incoming data from Flatworld and preparing it for use in the AthletiFi platform. The implementation should focus on robustness and efficiency to handle the expected data volume and ensure accurate aggregation of match events.

**Comment by qisforq** [comment]
Because the ingesting lambda will already have most likely added minutes_played into the match_attributes_per_player table, you must check to see if the record already exists first, and modify the existing record for that player for that match

**Comment by chef-louis** [comment]
- Completed trigger function `athletifi_aggregate_match_events`
- Added trigger `trg_aggregate_match_events` to execute function above after each newly inserted row in `match_events`

**Comment by chef-louis** [comment]
Quentin helped resolve subsequent issues in the player ratings trigger function and now we have ratings for the 2011 boys team with 3 matches of data!

**Comment by chef-louis** [comment]
Some further debugging required:
- Seeing a negative `shot_accuracy_score`  which is contributing to an overall negative `attack_rating` for player_id = `5d10640b-899f-4ff5-bf5b-b12f44fd948c`. This is mathematically occurring due to a low deviation score at the global level (0.028) and a relatively large difference in the player's accuracy (0.5) vs. player avg (0.91).
- We still shouldn't show negative and instead should show a minimum value so will need to revisit the white paper and update the trigger function accordingly.

**Comment by chef-louis** [comment]
Applied a ratings floor of 30 for now. The initial thought of having 60 caused an issue where many ratings scores were averaging lower and therefore the floor was used quite often. We can modify the floor relatively easily now though so we will discuss as a group to set the proper floor value.
