### ISSUE TITLE
Embed invite_id into the QR code URL to allow owner to claim ownership via scanning from the player card

### ISSUE THREAD

**Issue by chef-louis** [AthletiFi/athletifi-website#444]
- If the user scans the card for the first time and does not have an account yet, the user can be redirected to the profile page (or the dashboard player card)
- If the user already has an account and is logged in then the user should be redirected to the dashboard player card

Claude:
### Description:
Create a URL structure that serves both as an invite link for new user registration and as a redirect to the player's profile page for existing users. This URL will be used in QR codes on physical player cards.

### Key Components:
1. Design URL structure to include both invite ID and profile redirect parameters
2. Implement logic to handle the dual functionality of the URL:
   a. For new users: Process the invite and initiate account creation
   b. For existing users: Redirect to the player's profile page
3. Ensure the same URL works consistently for both initial registration and subsequent profile access
4. Integrate this new URL structure with the existing authentication system

### Acceptance Criteria:
- URL successfully includes both invite ID and profile redirect information
- New users scanning the QR code are directed to create an account using the invite link
- After account creation, users are redirected to the player's profile page
- Existing users scanning the QR code are immediately redirected to the player's profile page
- The system correctly distinguishes between new and existing users
- URL structure is compatible with QR code generation (though QR code generation itself is out of scope for this task)

**Comment by chef-louis** [comment]
Checked on this and good news is that the redirect already works. Here is an example of the URL structure:
`https://athleti.fi/login?invite_id=21d4eacf-a019-4922-82d5-deaa6085ba90&dashboard/summer-select-24/5`

**Comment by qisforq** [comment]
Awesome nice work @chef-louis! I need to talk through with you the best methods generating unique register links for all 360+ digital cards when you have time today
