### ISSUE TITLE
Integrate Jest and start building unit tests

### ISSUE THREAD

**Issue by chef-louis** [AthletiFi/athletifi-website#514]
AI-generated task details below:

# Task: Implement Unit Testing with Jest for AthletiFi Next.js Project

## Objective
Implement comprehensive unit tests for critical components and utility functions in our Next.js project using Jest.

## Background
Our AthletiFi project is built with Next.js and includes various components, utilities, and API integrations. To ensure code reliability and catch potential issues early, we need to implement unit tests for key parts of our application.

## Requirements

1. Set up Jest for Next.js:
   - Install necessary dependencies: `jest`, `@testing-library/react`, `@testing-library/jest-dom`
   - Configure Jest in `package.json` or create a `jest.config.js` file
   - Set up any required mocks for Next.js specific features (e.g., `next/router`)

2. Write unit tests for utility functions:
   - Focus on functions in `/src/app/utils/` directory
   - Priority functions to test:
     - `filterTargetArticle` in `helpers.ts`
     - `transformNotificationPreferences` in `fetchHelper.ts`
     - Functions in `dashboardHelper.ts`

3. Implement component tests:
   - Test critical components in `/src/components/` directory
   - Priority components:
     - `Header` component
     - `ProfileMain` component
     - `LatestMatch` component in dashboard

4. Test API helper functions:
   - Write tests for functions in `ApiHelper.ts`
   - Mock fetch requests and test error handling

5. Implement snapshot tests:
   - Create snapshot tests for key UI components to catch unexpected changes

6. Set up CI/CD integration:
   - Configure GitHub Actions or your preferred CI tool to run tests on every pull request

## Acceptance Criteria

- All new tests should pass successfully
- Achieve at least 70% code coverage for tested modules
- Include both positive and negative test cases
- Use meaningful test descriptions that explain the expected behavior
- Ensure tests run quickly (under 5 minutes for the entire suite)

## Resources

- Jest documentation: https://jestjs.io/docs/getting-started
- Testing Library documentation: https://testing-library.com/docs/
- Next.js testing documentation: https://nextjs.org/docs/testing

## Deliverables

- Updated `package.json` with testing scripts
- New test files alongside the components/utilities they're testing
- Updated README with instructions on how to run tests
- (Optional) Coverage report showing the extent of test coverage

**Comment by chef-louis** [comment]
- Added Jest libraries and config file
- Setup a basic unit-test on Custom404 component (simple, synchronous component)
- Able to run `yarn test` and have tests pass

**Comment by HectorAgudelo** [comment]
Jest is a versatile JavaScript testing framework, and you can use it to test a wide variety of things in your application. Here are a few key areas to focus on:
1. Unit Tests:
Pure Functions:
Test functions that take input and produce output without side effects. Ensure they return the correct values for various inputs, including edge cases.
Classes and Objects:
Test individual methods of classes and the interactions between them. Verify that objects are created and manipulated correctly.
Utility Functions:
Test any helper functions or modules that perform specific tasks, like formatting dates, validating input, or making API calls.
2. Integration Tests:
Component Interactions:
Test how different components interact with each other. This includes passing props, emitting events, and updating state.
API Integration:
Test interactions with external APIs, ensuring data is fetched and sent correctly.
Data Flow:
Verify that data flows through your application as expected, from input to output.
3. End-to-End Tests (E2E):
User Flows:
Test critical user flows in your application, such as sign-up, login, and checkout processes.
UI Interactions:
Verify that users can interact with the UI as expected, including clicking buttons, filling out forms, and navigating between pages.
Specific things to test:
Error Handling:
Test how your application handles errors, both expected and unexpected. Ensure that error messages are displayed correctly and that the application recovers gracefully.
Edge Cases:
Test scenarios that are not typical, such as empty inputs, invalid data, or large datasets.
Performance:
Test the performance of critical parts of your application to identify potential bottlenecks.
Remember that the goal of testing is to ensure your application works as expected and to catch potential errors before they reach production.

**Comment by chef-louis** [comment]
Jest unit testing plan by page

Hector
- "home" (root path)
- dashboard
- help-support
- profile
- settings
- about-us
- blog
- contact-us

Louis
- login
- logout
- privacy-policy
- qr-code
- register
- resolve-auth
- sign-up
- terms-of-use

**Comment by chef-louis** [comment]
Will create new tasks to cover ongoing unit testing with Jest
