### ISSUE TITLE
Research graph libraries that can match designs

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#81]
The goal is to find a library that offers bar charts and line charts that fit the design of the first two charts we will be focusing on for MVP (screenshots below).

Keep note of the overlay option for the line chart, with a side bar of the different metrics that can be overlayed on the main chart.

<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/fe3ba59c-16e6-47b7-98a8-d408998df532" width="500">
<img src="https://github.com/AthletiFi/athletifi-website/assets/33239211/3fda5733-a4e8-402f-a101-e8af1686c16e" width="500">

**Comment by chef-louis** [comment]
- [D3](https://d3js.org/)
  - Pros: Considered the most flexible and customizable
  - Cons: Steep learning curve; can be difficult to integrate charts within applications
- [Recharts](https://recharts.org/en-US/):
  - Pros: handles most graph types; most popular react library with good documentation
  - Cons: stylistically somewhat simple
- [VISX](https://airbnb.io/visx):
  - Pros: Built to be an in-between option with good customized styling while attempting to be straight forward with usage; supports [radar chart](https://airbnb.io/visx/radar) (ie. spider chart)
  - Cons: ??
- [Nivo](https://nivo.rocks/)
  - Pros: Built for customized styling
  - Cons: Not as popular as other libraries; documentation may not be as rigorous

**Comment by chef-louis** [comment]
Tried out both Recharts and VISX.

- Recharts was by far easier to work with and intuitively make changes. There are modular components within Recharts to include/exclude options such as tooltips, legends, etc and the documentations for props is easier to understand / follow.
- VISX has a naturally clean look/feel to it and the customization options appear to all be there but there is considerably more code that needs to be written to get even simple functionality added.

Recommendation is to try pushing forward with Recharts -- we should be able to get good functionality out of it but if we run into stylistic limitations we may want to invest some time in learning VISX.

**Comment by chef-louis** [comment]
![Image](https://github.com/AthletiFi/athletifi-website/assets/140190642/424ca5d5-7a48-4fa7-82f2-8436ebbc0c7d)

**Comment by chef-louis** [comment]
Synced up with Paula and agreed to push forward with Rechart for now as it handles most of the design elements we are looking for without too much coding. A few styling updates to make/try to the current charts:

- [ ] Remove the word "Rating" from the tool-tip on the barchart
- [ ] Fix the tool-tip window to the right of the bar chart and add metric detail/info within tool-tip window
- [ ] Shrink the bar chart along width axis
- [ ] Update date axis of line-chart to use match #'s instead
- [ ] Expand the legend on the x-axis of the line-chart to have the tool-tip numbers show there instead of next to the cursor

**Comment by chef-louis** [comment]
Able to achieve desired customization without a ton of complexity. Recharts is the best option to move forward with based on our experiences so far.
