### ISSUE TITLE
Dynamic URL routing for existing dashboard URLs

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#83]
- [ ] Implement dynamic routing for player cards
  - [x] Create a dynamic route parameter in the Next.js page (`/dashboard/vsa-23/[playerId]`).
  - [ ] Work with @HectorAgudelo to link to the Dashboard component he is working on
  - [x] Ensure the Dashboard page can parse and use the player ID from the URL.
- [x] Display a custom 'Dashboard 404' for invalid URLs, but which include `/dashboard` in the URL.
- [x] TODO: update the look of the custom Dashboard 404

**Comment by qisforq** [comment]
Full list of Dashboard links for VSA collection:

[VSA_Collection_QR_Code_CSV.csv](https://github.com/AthletiFi/athletifi-website/files/14102993/VSA_Collection_QR_Code_CSV.csv)

**Comment by chef-louis** [comment]
@HectorAgudelo I've incorporated the existing Dashboard layout/structure into the dynamic routing for now. When you're ready with the new dashboard layout, I can update the dynamic routing to use that component instead.
