### ISSUE TITLE
Create S3 buckets for storing logos for RDS database

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#97]
**Objective**: Implement Amazon S3 integration for storing club logos and player card images, so that their URLS can be stored in the RDS database.

- [x] **Set Up Amazon S3 Buckets**:

   - [x] Create three S3 buckets: one for logos and another for player card images. 
   - [x] Configure the buckets for public access.
 

- [x] **Store Image URLs in Amazon RDS**:

   - [x] After successfully uploading an image to S3, obtain the public URL of the image.
   - [x] Update the respective `logo_svg_url` or `card_image_url` field in our Amazon RDS `clubs` or `players` table with the new S3 URL.

**Comment by chef-louis** [comment]
Created a AWS S3 Bucket names `athletifi-s3` with the following folders: `logos` and `player-card-images`. This S3 bucket is NOT blocking public access to its contents and I've updated the bucket policy to automatically tag new files/objects as public for accessibility by the front-end application.

**Comment by chef-louis** [comment]
Adding request from @qisforq:

- [ ] Create another S3 bucket for player_avatar

**Comment by chef-louis** [comment]
S3 folder called `player-avatars` added to the public S3 bucket

**Comment by chef-louis** [comment]
Thanks @qisforq for the lift on adding the URLs into the database. I'm going to close out this task as complete.
